<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable><ImplicitUsings>disable</ImplicitUsings>
    <ApplicationManifest>../QuietDesk.DesktopProbe/app.manifest</ApplicationManifest>
    <NoWarn>$(NoWarn);WFO0003</NoWarn><AssemblyName>QuietDesk</AssemblyName>
    <Version>0.5.2</Version>
    <ApplicationIcon>Assets/quietdesk.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
    <Content Include="Assets/**/*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../docs/SOUND-LICENSES.md" Link="SOUND-LICENSES.md" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../docs/licenses/*" Link="licenses/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="../QuietDesk.DesktopProbe/Native.cs" Link="Desktop/Native.cs" />
  </ItemGroup>
</Project>
