using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Threading;
using System.Text.Json;
namespace QuietDesk;
internal static class RevisionVerification
{
    private static string Output(string[] args){int i=Array.IndexOf(args,"--out");return i>=0?args[i+1]:Path.Combine(AppContext.BaseDirectory,"revision-test.txt");}
    private static Application App(){var app=new Application{ShutdownMode=ShutdownMode.OnExplicitShutdown};app.Resources.MergedDictionaries.Add(new(){Source=new Uri("/QuietDesk;component/UI/Theme.xaml",UriKind.Relative)});return app;}
    private static void Wait(Task task){var frame=new DispatcherFrame();task.ContinueWith(_=>Application.Current.Dispatcher.BeginInvoke(()=>frame.Continue=false));Dispatcher.PushFrame(frame);task.GetAwaiter().GetResult();}
    internal static int Run(string[] args){var lines=new List<string>();try{var app=App();using var model=new PlayerModel(Path.Combine(Path.GetTempPath(),"QuietDesk-revision-"+Guid.NewGuid()));model.Master=0;Wait(model.PlayFile(Path.Combine(AppContext.BaseDirectory,"Assets","Sounds","rain.wav")));if(!model.Playing||!model.HasMedia)throw new Exception("local source failed");Wait(model.ToggleMedia());if(!model.MediaPaused||!model.Playing)throw new Exception("independent pause stopped ambient");Wait(model.TogglePlay());Wait(model.TogglePlay());if(!model.MediaPaused)throw new Exception("global resume erased individual pause");lines.Add("PASS independent media pause survives global pause / resume");Wait(model.ToggleMedia());if(model.MediaPaused)throw new Exception("local resume failed");lines.Add("PASS local media resumes without reopening source");Wait(model.SelectDevice(null));if(!model.Playing)throw new Exception("device selection lost playback");lines.Add("PASS default output selection preserves state");Wait(model.TogglePlay());Wait(model.SelectDevice(null));if(model.Playing)throw new Exception("device change autoplay");lines.Add("PASS paused device selection does not autoplay");model.PreviewFeedback();if(!model.Status.Contains("静音"))throw new Exception("silent preview missing explanation");if(InteractionFeedback.Samples(0,true).Any(x=>x!=0)||!InteractionFeedback.Samples(.5,true).Any(x=>Math.Abs(x)>.01))throw new Exception("feedback amplitude");lines.Add("PASS feedback mute explanation and nonzero preview signal");if(RadioDirectory.Domestic().Count<2||RadioDirectory.Domestic().Any(s=>!s.DirectConnection||!RadioDirectory.IsHttp(s.Url)))throw new Exception("domestic catalog invalid");lines.Add("PASS domestic catalog available without network");File.WriteAllLines(Output(args),lines);return 0;}catch(Exception e){lines.Add("FAIL "+e);File.WriteAllLines(Output(args),lines);return 1;}}
    internal static int Desktop(string[] args){var lines=new List<string>();try{var app=App();var folder=Path.Combine(Path.GetTempPath(),"QuietDesk-desktop-"+Guid.NewGuid());Directory.CreateDirectory(folder);File.WriteAllText(Path.Combine(folder,"placement.json"),"{\"Edge\":\"right\"}");using var model=new PlayerModel(folder);using var host=new DesktopHost(lines.Add,folder,h=>DesktopCard.Create(model,h,()=>{}));Wait(Task.Delay(150));if(host.Handle==0)throw new Exception("No desktop child");lines.Add(host.Inspect());host.SetCollapsed(true);Wait(Task.Delay(100));QuietDesk.DesktopProbe.Native.GetWindowRect(host.Handle,out var small);var scale=QuietDesk.DesktopProbe.Native.GetDpiForWindow(host.Handle)/96.0;if(Math.Abs((small.Right-small.Left)-8*scale)>1)throw new Exception("hidden hit area too wide");lines.Add("PASS collapsed native window is only 8 DIP wide");host.SetCollapsed(false);Wait(Task.Delay(100));QuietDesk.DesktopProbe.Native.GetWindowRect(host.Handle,out var full);if(Math.Abs((full.Right-full.Left)-220*scale)>1)throw new Exception("expand width mismatch");lines.Add("PASS expanded native window is 220 DIP wide");lines.Add(host.Inspect());File.WriteAllLines(Output(args),lines);return 0;}catch(Exception e){lines.Add("FAIL "+e);File.WriteAllLines(Output(args),lines);return 1;}}
    internal static int Domestic(string[] args){var results=new List<object>();foreach(var station in RadioDirectory.Domestic()){var watch=System.Diagnostics.Stopwatch.StartNew();try{using var session=MediaSession.Open(station.Url,true,CancellationToken.None,station.Format,true).GetAwaiter().GetResult();var data=new float[8192];float peak=0;for(int i=0;i<35;i++){session.Provider!.Read(data,0,data.Length);peak=Math.Max(peak,data.Max(x=>Math.Abs(x)));Thread.Sleep(90);}if(peak<.00001)throw new IOException("No decoded signal");results.Add(new{station.Name,station.Url,station.Format,status="decoded-no-proxy",peak,seconds=watch.Elapsed.TotalSeconds,note="未修改VPN；操作系统隧道路由仍需用户核验"});}catch(Exception e){results.Add(new{station.Name,station.Url,status="failed",error=e.Message,seconds=watch.Elapsed.TotalSeconds});}}File.WriteAllText(Output(args),JsonSerializer.Serialize(results,new JsonSerializerOptions{WriteIndented=true}));return results.Count==0?1:0;}
}
