using System;
using System.IO;
using System.Linq;
using System.Text;
namespace QuietDesk.Reading;
internal static class ReadingVerification
{
    internal static int Run(string[] args){if(args.Contains("--layout"))return Layout(args);if(args.Contains("--cancel-check"))return CancelCheck(args).GetAwaiter().GetResult();if(args.Contains("--worker-check"))return WorkerCheck(args).GetAwaiter().GetResult();if(args.Contains("--live"))return Live(args).GetAwaiter().GetResult();int oi=Array.IndexOf(args,"--out");string output=oi<0?"reading-test.txt":args[oi+1];var lines=new System.Collections.Generic.List<string>();void Check(bool ok,string name){if(!ok)throw new Exception(name);lines.Add("PASS "+name);}try{
        var source=ReadingCatalog.All()[0];string xml="<rss><channel><item><title>Study</title><link>https://example.org/10.1234/test?utm_source=x</link><pubDate>2026-09-12</pubDate><description><![CDATA[<p>Abstract</p><script>bad</script>]]></description></item></channel></rss>";var items=ReadingContent.Parse(Encoding.UTF8.GetBytes(xml),source);Check(items.Count==1&&items[0].PublishedDay=="2026-09-12"&&items[0].Abstract=="Abstract","RSS dates, HTML cleaning and parsing");Check(items[0].Doi=="10.1234/test"&&!items[0].Url.Contains("utm_"),"DOI identity and tracking normalization");
        try{ReadingContent.Parse(Encoding.UTF8.GetBytes("<!DOCTYPE rss [<!ENTITY x SYSTEM 'file:///c:/windows/win.ini'>]><rss>&x;</rss>"),source);throw new Exception("DTD allowed");}catch(System.Xml.XmlException){lines.Add("PASS external XML entities rejected");}
        var settings=new ReadingSettings();settings.SetKey("fixture-key-not-real");Check(!System.Text.Json.JsonSerializer.Serialize(settings).Contains("fixture-key-not-real")&&settings.Key=="fixture-key-not-real"&&!settings.ProtectedKey.Contains("fixture"),"current-user secret protection");
        string dir=Path.Combine(Path.GetTempPath(),"QuietDesk-reading-test-"+Guid.NewGuid());var store=new ReadingStore(dir);store.Put("article",items[0].Id,items[0]);store.Put("article",items[0].Id,items[0]);Check(store.Load<Article>("article").Count==1,"SQLite duplicate identity upsert");Check(Enumerable.Range(0,50).All(_=>store.Reserve("2026-09-12",50))&&!store.Reserve("2026-09-12",50)&&new ReadingStore(dir).Reserve("2026-09-13",50),"persisted daily quota and day rollover");
        Check(ReadingContent.ExtractHtml("<html>Login to read</html>","aps").Error.Length>0,"missing full text is not summarized as complete");
        var vm=new ReadingViewModel(Path.Combine(dir,"disabled"));Check(vm.Service==null&&!Directory.Exists(Path.Combine(dir,"disabled")),"disabled module creates no database or polling");vm.Dispose();
        Check(IdleGate.CanRun(180000,30,true,false)&&!IdleGate.CanRun(179999,30,true,false)&&!IdleGate.CanRun(180000,29,true,false)&&!IdleGate.CanRun(180000,30,false,false)&&!IdleGate.CanRun(180000,30,true,true),"idle, low CPU, AC and presentation gates");
        var apiSettings=new ReadingSettings{Endpoint="https://fixture.invalid/v1",Model="fixture"};apiSettings.SetKey("fixture-key-not-real");var handler=new FixtureHandler();using(var api=new SummaryClient(handler)){Check(api.Ask(apiSettings,"A sufficiently long abstract with scientific evidence.",false,default).GetAwaiter().GetResult()=="测试标题\n测试摘要","compatible API response parsing");Check(handler.Body.Contains("max_tokens")&&!handler.Body.Contains("fixture-key-not-real")&&!handler.Body.Contains("\"tools\""),"API payload excludes secrets and tool execution");handler.Fail=true;try{api.Ask(apiSettings,"fixture",false,default).GetAwaiter().GetResult();throw new Exception("rate limit ignored");}catch(IOException e){Check(e.Message.Contains("限流"),"rate limit is explicit and not retried");}}
        var unknown=ReadingContent.Parse(Encoding.UTF8.GetBytes("<feed xmlns='http://www.w3.org/2005/Atom'><entry><title>Atom item</title><link href='https://example.org/atom'/><updated>2026-09-12T12:00:00Z</updated></entry></feed>"),source).Single();Check(unknown.PublishedDay==null,"Atom update time is not misreported as publication time");
        var oldArticle=new Article{Id="old",Discovered=DateTimeOffset.Now.AddDays(-100)};var favorite=new Article{Id="favorite",Discovered=oldArticle.Discovered,Favorite=true};store.Put("article",oldArticle.Id,oldArticle);store.Put("article",favorite.Id,favorite);store.Prune();Check(store.Find<Article>("article","old")==null&&store.Find<Article>("article","favorite")!=null,"retention removes expired ordinary items but preserves favorites");
        Check(store.Query("2026-09-12","",false,false,0).Count==1,"database date filtering and paging");
        File.WriteAllLines(output,lines);return 0;
    }catch(Exception e){lines.Add("FAIL "+e);File.WriteAllLines(output,lines);return 1;}}

    private static async System.Threading.Tasks.Task<int> Live(string[] args){int oi=Array.IndexOf(args,"--out");string output=args[oi+1];var rows=new System.Collections.Generic.List<object>();using var client=ReadingContent.Client();foreach(var source in ReadingCatalog.All()){try{using var response=await client.GetAsync(source.Url,System.Net.Http.HttpCompletionOption.ResponseHeadersRead);var bytes=await ReadingContent.Bounded(response,4000000,default);var articles=ReadingContent.Parse(bytes,source);rows.Add(new{source.Name,source.Url,status=(int)response.StatusCode,count=articles.Count,result=articles.Count>0?"parsed":"empty",sample=articles.FirstOrDefault()?.Title});}catch(Exception e){rows.Add(new{source.Name,source.Url,result="failed",error=e.Message});}File.WriteAllText(output,System.Text.Json.JsonSerializer.Serialize(rows,new System.Text.Json.JsonSerializerOptions{WriteIndented=true}));}return 0;}

    private static async System.Threading.Tasks.Task<int> WorkerCheck(string[] args){string output=args[Array.IndexOf(args,"--out")+1];var request=new WorkerRequest();int fi=Array.IndexOf(args,"--pdf"),ui=Array.IndexOf(args,"--url");if(fi>=0)request.File=args[fi+1];if(ui>=0){request.Url=args[ui+1];request.Publisher=args.Contains("--aps")?"aps":"nature";}var started=System.Diagnostics.Stopwatch.StartNew();long peak=0;double cpu=0;var task=ReadingWorker.Launch(request,Path.Combine(Path.GetDirectoryName(output)!,"worker-cache"),default);while(!task.IsCompleted){foreach(var id in ReadingWorker.Processes.Keys)try{using var p=System.Diagnostics.Process.GetProcessById(id);peak=Math.Max(peak,p.PrivateMemorySize64);cpu=Math.Max(cpu,p.TotalProcessorTime.TotalSeconds);}catch{}await System.Threading.Tasks.Task.Delay(20);}try{var result=await task;File.WriteAllText(output,System.Text.Json.JsonSerializer.Serialize(new{elapsedSeconds=started.Elapsed.TotalSeconds,peakPrivateBytes=peak,cpuSeconds=cpu,result.Basis,result.Complete,result.Error,characters=result.Text.Length,sample=result.Text[..Math.Min(500,result.Text.Length)]},new System.Text.Json.JsonSerializerOptions{WriteIndented=true}));return result.Error.Length==0?0:1;}catch(Exception e){File.WriteAllText(output,e.ToString());return 1;}}

    private sealed class FixtureHandler:System.Net.Http.HttpMessageHandler{
        internal string Body="";internal bool Fail;
        protected override async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> SendAsync(System.Net.Http.HttpRequestMessage request,System.Threading.CancellationToken token){Body=await request.Content!.ReadAsStringAsync(token);return new System.Net.Http.HttpResponseMessage(Fail?System.Net.HttpStatusCode.TooManyRequests:System.Net.HttpStatusCode.OK){Content=new System.Net.Http.StringContent("{\"choices\":[{\"message\":{\"content\":\"测试标题\\n测试摘要\"}}]}")};}
    }

    private static int Layout(string[] args){string output=args[Array.IndexOf(args,"--out")+1];var app=new System.Windows.Application();app.Resources.MergedDictionaries.Add(new System.Windows.ResourceDictionary{Source=new Uri("/QuietDesk;component/UI/Theme.xaml",UriKind.Relative)});string dir=Path.Combine(Path.GetTempPath(),"QuietDesk-layout-"+Guid.NewGuid());using var model=new ReadingViewModel(dir);model.Enable();var store=new ReadingStore(Path.Combine(dir,"reading"));for(int i=0;i<40;i++)store.Put("article",i.ToString(),new Article{Id=i.ToString(),Title="Long research title: testing clear reading, numerical results and scientific uncertainty",ChineseTitle="测试文章：清晰呈现研究结果与局限",SourceName="Physical Review Letters",PublishedDay=DateTime.Now.ToString("yyyy-MM-dd"),Status="基于摘要／导读"});var view=new ReadingView(model);view.RaiseEvent(new System.Windows.RoutedEventArgs(System.Windows.FrameworkElement.LoadedEvent));view.Measure(new System.Windows.Size(760,560));view.Arrange(new System.Windows.Rect(0,0,760,560));view.UpdateLayout();var bitmap=new System.Windows.Media.Imaging.RenderTargetBitmap(760,560,96,96,System.Windows.Media.PixelFormats.Pbgra32);bitmap.Render(view);var encoder=new System.Windows.Media.Imaging.PngBitmapEncoder();encoder.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(bitmap));using(var file=File.Create(output))encoder.Save(file);view.RaiseEvent(new System.Windows.RoutedEventArgs(System.Windows.FrameworkElement.UnloadedEvent));app.Shutdown();return 0;}
    private static async System.Threading.Tasks.Task<int> CancelCheck(string[] args){string output=args[Array.IndexOf(args,"--out")+1];var listener=new System.Net.HttpListener();var socket=new System.Net.Sockets.TcpListener(System.Net.IPAddress.Loopback,0);socket.Start();int port=((System.Net.IPEndPoint)socket.LocalEndpoint).Port;socket.Stop();listener.Prefixes.Add($"http://127.0.0.1:{port}/");listener.Start();using var cancel=new System.Threading.CancellationTokenSource();var task=ReadingWorker.Launch(new WorkerRequest{Url=$"http://127.0.0.1:{port}/"},Path.Combine(Path.GetTempPath(),"QuietDesk-cancel-"+Guid.NewGuid()),cancel.Token);try{var context=await listener.GetContextAsync().WaitAsync(TimeSpan.FromSeconds(10));var watch=System.Diagnostics.Stopwatch.StartNew();cancel.Cancel();try{await task;throw new Exception("Worker did not cancel");}catch(OperationCanceledException){}if(ReadingWorker.Processes.Count!=0||watch.Elapsed.TotalSeconds>10)throw new Exception("Worker cancellation left process or exceeded deadline");File.WriteAllText(output,$"PASS active network worker canceled and exited in {watch.Elapsed.TotalSeconds:F3} seconds; no child remains");return 0;}finally{cancel.Cancel();listener.Close();try{await task;}catch{}}}
}
