using System;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using Microsoft.Win32;
namespace QuietDesk.Reading;
internal sealed class ReadingViewModel:IDisposable
{
    internal DateTime SelectedDay {get;set;}=DateTime.Today;internal int SelectedPage {get;set;}
    internal string Directory {get;}internal ReadingSettings Settings {get;private set;}internal ReadingService? Service {get;private set;}internal string Error {get;private set;}="";
    internal ReadingViewModel(string directory){Directory=directory;Settings=ReadingService.LoadSettings(directory);if(Settings.Enabled)try{Service=new(System.IO.Path.Combine(directory,"reading"),Settings);}catch(Exception e){Error="阅读数据暂不可用："+e.Message;}}
    internal void Enable(){try{Service??=new(System.IO.Path.Combine(Directory,"reading"),Settings);Settings.Enabled=true;ReadingService.SaveSettings(Directory,Settings);Error="";}catch(Exception e){Error="无法启用阅读："+e.Message;}}
    internal void Disable(){Settings.Enabled=false;ReadingService.SaveSettings(Directory,Settings);Service?.Dispose();Service=null;}
    public void Dispose()=>Service?.Dispose();
}
internal sealed class ReadingView:UserControl
{
    private readonly ReadingViewModel model;private readonly DockPanel shell=new();private readonly ContentControl body=new();private readonly TextBlock status=Ui.Text("",12);private int page;private int articleOffset;private ListBox? list;private DatePicker? date;private ComboBox? filter;private CheckBox? discovered;private bool loaded;
    internal ReadingView(ReadingViewModel model){this.model=model;page=model.SelectedPage;FontFamily=new FontFamily("Microsoft YaHei UI");FontSize=13;Background=Ui.B("#222224");Content=shell;var tabs=new WrapPanel();DockPanel.SetDock(tabs,Dock.Top);shell.Children.Add(tabs);foreach(var pair in new[]{("今日",0),("订阅",1),("收藏",2),("阅读设置",3)}){var b=Ui.Button(pair.Item1,()=>Show(pair.Item2),feedback:false);b.Margin=new Thickness(0,0,8,12);tabs.Children.Add(b);}DockPanel.SetDock(status,Dock.Bottom);shell.Children.Add(status);shell.Children.Add(body);Loaded+=(_,_)=>{loaded=true;if(model.Service!=null)model.Service.Updated+=Update;Show(page);};Unloaded+=(_,_)=>{loaded=false;if(model.Service!=null)model.Service.Updated-=Update;if(list!=null)list.ItemsSource=null;body.Content=null;};}
    private void Update(){if(!loaded)return;Dispatcher.BeginInvoke(()=>{if(!loaded)return;status.Text=model.Service?.Status??"";if(page is 0 or 2)RefreshList();});}
    private StackPanel Stack()=>new(){Margin=new Thickness(0,4,0,8)};
    private void Show(int selected){page=selected;model.SelectedPage=selected;articleOffset=0;list=null;if(model.Service==null){var p=Stack();p.Children.Add(Ui.Text("把值得读的内容，留在这里。",24));Ui.Gap(p);p.Children.Add(Ui.Text("启用后自行选择期刊，不会自动订阅、弹窗或播放提示音。尚未配置API也能浏览文章。"));p.Children.Add(Ui.Button("启用阅读",()=>{model.Enable();if(model.Service!=null)model.Service.Updated+=Update;Show(1);},feedback:false));p.Children.Add(Ui.Text(model.Error,12));body.Content=p;return;}
        body.Content=selected switch{1=>Subscriptions(),3=>Settings(),_=>Articles()};status.Text=model.Service.Status;}
    private UIElement Articles(){var p=new DockPanel();var controls=new WrapPanel();date=new DatePicker{Foreground=Ui.B("#FCFCFC"),Background=Ui.B("#222224"),SelectedDate=model.SelectedDay,Width=130,Margin=new Thickness(0,0,8,8)};var dateBorder=new FrameworkElementFactory(typeof(Border));dateBorder.SetValue(Border.BackgroundProperty,Ui.B("#111111"));dateBorder.SetValue(Border.BorderBrushProperty,Ui.B("#514B57"));dateBorder.SetValue(Border.BorderThicknessProperty,new Thickness(1));dateBorder.SetValue(Border.CornerRadiusProperty,new CornerRadius(6));var dateHost=new FrameworkElementFactory(typeof(ScrollViewer));dateHost.Name="PART_ContentHost";dateHost.SetValue(FrameworkElement.MarginProperty,new Thickness(6));dateBorder.AppendChild(dateHost);var dateStyle=new Style(typeof(System.Windows.Controls.Primitives.DatePickerTextBox));dateStyle.Setters.Add(new Setter(Control.ForegroundProperty,Ui.B("#FCFCFC")));dateStyle.Setters.Add(new Setter(Control.TemplateProperty,new ControlTemplate(typeof(System.Windows.Controls.Primitives.DatePickerTextBox)){VisualTree=dateBorder}));date.Resources.Add(typeof(System.Windows.Controls.Primitives.DatePickerTextBox),dateStyle);
        date.SelectedDateChanged+=(_,_)=>{articleOffset=0;model.SelectedDay=date.SelectedDate??DateTime.Today;RefreshList();};controls.Children.Add(date);filter=new ComboBox{Width=180,ItemsSource=new[]{new Source{Id="",Name="全部刊物"}}.Concat(model.Service!.Sources()).ToList(),SelectedIndex=0,Margin=new Thickness(0,0,8,8)};filter.SelectionChanged+=(_,_)=>{articleOffset=0;RefreshList();};controls.Children.Add(filter);discovered=new CheckBox{Content="按发现日期",Margin=new Thickness(0,0,8,8)};discovered.Checked+=(_,_)=>RefreshList();discovered.Unchecked+=(_,_)=>RefreshList();controls.Children.Add(discovered);controls.Children.Add(Ui.Button("检查更新",async()=>{await model.Service.Refresh();RefreshList();},feedback:false));DockPanel.SetDock(controls,Dock.Top);p.Children.Add(controls);
        list=new ListBox{Background=Brushes.Transparent,BorderThickness=new Thickness(0),Foreground=Ui.B("#FCFCFC"),};VirtualizingPanel.SetIsVirtualizing(list,true);VirtualizingPanel.SetVirtualizationMode(list,VirtualizationMode.Recycling);ScrollViewer.SetCanContentScroll(list,true);var style=new Style(typeof(ListBoxItem));style.Setters.Add(new Setter(Control.PaddingProperty,new Thickness(12)));style.Setters.Add(new Setter(Control.HorizontalContentAlignmentProperty,HorizontalAlignment.Stretch));list.ItemContainerStyle=style;var factory=new FrameworkElementFactory(typeof(TextBlock));factory.SetBinding(TextBlock.TextProperty,new Binding("Display"));factory.SetValue(TextBlock.TextWrappingProperty,TextWrapping.Wrap);factory.SetValue(TextBlock.FontSizeProperty,13.0);list.ItemTemplate=new DataTemplate{VisualTree=factory};list.MouseDoubleClick+=(_,_)=>{if(list.SelectedItem is Article a)Detail(a);};
        var actions=new WrapPanel();var moreMenu=new ContextMenu{Background=Ui.B("#222224"),Foreground=Ui.B("#FCFCFC")};actions.Children.Add(Ui.Button("上一页",()=>{articleOffset=Math.Max(0,articleOffset-200);RefreshList();},feedback:false));actions.Children.Add(Ui.Button("下一页",()=>{if(list.Items.Count==200){articleOffset+=200;RefreshList();}},feedback:false));foreach(var pair in new[]{("阅读摘要",0),("生成短总结",1),("收藏／取消收藏",2),("打开原文",3),("精读",4),("导入PDF精读",5),("立即处理",6),("取消精读",7)}){Action action=async()=>{if(list.SelectedItem is not Article a)return;try{switch(pair.Item2){case 0:Detail(a);break;case 1:await model.Service.Summarize(a);Detail(a);break;case 2:a.Favorite=!a.Favorite;model.Service.SaveArticle(a);break;case 3:Open(a.Url);break;case 4:if(FullConsent())model.Service.Queue(a);break;case 5:if(FullConsent()){var dialog=new OpenFileDialog{Filter="PDF 文档|*.pdf"};if(dialog.ShowDialog()==true)model.Service.Queue(a,dialog.FileName);}break;case 6:model.Service.RunNow(a.Id);break;case 7:model.Service.Cancel(a.Id);break;}}catch(Exception ex){status.Text=ex.Message;}};if(pair.Item2<=1)actions.Children.Add(Ui.Button(pair.Item1,action,feedback:false));else{var item=new MenuItem{Header=pair.Item1};item.Click+=(_,_)=>action();moreMenu.Items.Add(item);}}var more=Ui.Button("更多操作",()=>{moreMenu.IsOpen=true;},feedback:false);moreMenu.PlacementTarget=more;more.ContextMenu=moreMenu;actions.Children.Add(more);DockPanel.SetDock(actions,Dock.Bottom);p.Children.Add(actions);p.Children.Add(list);RefreshList();return p;}
    private void RefreshList(){if(list==null||date==null)return;var id=(list.SelectedItem as Article)?.Id;string day=(date.SelectedDate??DateTime.Today).ToString("yyyy-MM-dd"),source=(filter?.SelectedItem as Source)?.Id??"";var articles=model.Service!.Query(day,source,discovered?.IsChecked==true,page==2,articleOffset);list.ItemsSource=articles;if(id!=null)list.SelectedItem=articles.FirstOrDefault(a=>a.Id==id);status.Text=$"本页 {articles.Count} 篇（从第{articleOffset+1}篇起） · 双击阅读 · {model.Service.Status}";}
    private void Detail(Article a){a.Read=true;model.Service!.SaveArticle(a);var text=new TextBox{Text=a.Title+"\n"+a.SourceName+" · "+(a.PublishedDay??"日期待确认")+"\n"+a.DateEvidence+"\n\n"+(a.Summary.Length>0?a.Summary:"原始摘要／导读：\n"+a.Abstract)+"\n\n"+a.FullSummary,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Margin=new Thickness(18)};var w=new Window{Title="阅读 · "+a.SourceName,Width=720,Height=650,MinWidth=400,MinHeight=300,Owner=Window.GetWindow(this),Content=text,Background=Ui.B("#111111"),WindowStartupLocation=WindowStartupLocation.CenterOwner};WindowChrome.DarkTitle(w);w.ShowDialog();}
    private bool FullConsent(){var settings=model.Settings;if(!settings.Ready){status.Text="请先配置摘要API。";return false;}if(settings.FullConsent==settings.Endpoint)return true;if(MessageBox.Show(Window.GetWindow(this),"精读会将获取或导入的全文文本发送到：\n"+settings.Endpoint+"\n请确认你的服务与访问许可允许此用途。此选择仅记住当前服务地址。","全文发送范围",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return false;settings.FullConsent=settings.Endpoint;model.Service!.Configure(settings);return true;}
    private UIElement Subscriptions(){var p=Stack();p.Children.Add(Ui.Text("选择你的刊物",24));p.Children.Add(Ui.Text("首次收集最近七天可取得的文章；订阅源不保证覆盖全部历史。"));foreach(var s in model.Service!.Sources()){var row=Stack();var check=new CheckBox{Content=s.Name,IsChecked=s.Subscribed};check.Click+=(_,_)=>{s.Subscribed=check.IsChecked==true;model.Service.SaveSource(s);};row.Children.Add(check);row.Children.Add(Ui.Text(s.Status+" · 最近成功："+(s.LastSuccess?.ToLocalTime().ToString("g")??"尚无"),12));p.Children.Add(row);}Ui.Gap(p);var name=new TextBox{ToolTip="刊物名称",Margin=new Thickness(0,4,0,4)};var url=new TextBox{ToolTip="RSS／Atom 地址",Margin=new Thickness(0,4,0,4)};p.Children.Add(Ui.Text("自定义订阅：名称与RSS／Atom地址"));p.Children.Add(name);p.Children.Add(url);p.Children.Add(Ui.Button("添加订阅",()=>{if(name.Text.Trim().Length==0||!ReadingCatalog.Http(url.Text.Trim())){status.Text="请输入名称及有效HTTP(S)订阅地址。";return;}var s=new Source{Id="custom-"+ReadingCatalog.Hash(url.Text.Trim()),Name=name.Text.Trim(),Url=url.Text.Trim(),Publisher="news",Subscribed=true};model.Service.SaveSource(s);Show(1);},feedback:false));p.Children.Add(Ui.Button("检查并刷新状态",async()=>{await model.Service.Refresh();Show(1);},feedback:false));return new ScrollViewer{Content=p};}
    private UIElement Settings(){var p=Stack();p.Children.Add(Ui.Text("摘要服务",24));p.Children.Add(Ui.Text("兼容 Chat Completions 的HTTPS接口；可填写以 /v1 结尾的服务地址。密钥仅保存在本机当前用户下。"));var endpoint=new TextBox{Text=model.Settings.Endpoint};var name=new TextBox{Text=model.Settings.Model};var key=new PasswordBox{ToolTip="留空保留现有密钥",MinHeight=34};var automatic=new CheckBox{Content="自动生成中文摘要（会发送标题和摘要／导读，可能产生费用）",IsChecked=model.Settings.Automatic};var limit=new TextBox{Text=model.Settings.DailyLimit.ToString()};foreach(var pair in new[]{("API地址",(UIElement)endpoint),("模型名称",name),("API密钥（留空保留）",key),("每日自动篇数；手动生成不计入此额度",limit)}){Ui.Gap(p);p.Children.Add(Ui.Text(pair.Item1));p.Children.Add(pair.Item2);}Ui.Gap(p);p.Children.Add(automatic);
        bool Save(){if(!Uri.TryCreate(endpoint.Text.Trim(),UriKind.Absolute,out var uri)||uri.Scheme!="https"||uri.UserInfo.Length>0||uri.Query.Length>0){status.Text="请输入不含密码或查询参数的HTTPS API地址。";return false;}if(!int.TryParse(limit.Text,out var count)||count<1||count>500){status.Text="每日篇数范围为1–500。";return false;}string address=endpoint.Text.Trim().TrimEnd('/');if(model.Settings.AbstractConsent!=address&&MessageBox.Show(Window.GetWindow(this),"生成摘要会发送文章标题和摘要／导读到：\n"+address+"\n是否允许？","摘要发送范围",MessageBoxButton.OKCancel)!=MessageBoxResult.OK)return false;model.Settings.Endpoint=address;model.Settings.Model=name.Text.Trim();if(key.Password.Length>0)model.Settings.SetKey(key.Password);model.Settings.AbstractConsent=address;model.Settings.Automatic=automatic.IsChecked==true;model.Settings.DailyLimit=count;model.Service!.Configure(model.Settings);status.Text="阅读设置已保存。";return true;}
        p.Children.Add(Ui.Button("停用阅读后台",()=>{if(model.Service!=null)model.Service.Updated-=Update;model.Disable();Show(3);},feedback:false));
        p.Children.Add(Ui.Button("保存设置",()=>Save(),feedback:false));p.Children.Add(Ui.Button("测试连接",async()=>{if(!Save())return;try{status.Text=await model.Service!.Test();}catch(Exception ex){status.Text=ex.Message;}},feedback:false));p.Children.Add(Ui.Text("轻量订阅每两小时检查。全文等待闲置三分钟、低CPU、接通电源且无全屏／演示时处理；每次仅一篇。文章90天、收藏长期保留，全文缓存上限200MB。",12));return new ScrollViewer{Content=p};}
    private static void Open(string url){if(ReadingCatalog.Http(url))System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(url){UseShellExecute=true});}
}
