using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.NetworkInformation;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
namespace QuietDesk.Reading;
internal sealed class ReadingService:IDisposable
{
    private readonly ReadingStore store;private readonly HttpClient http=ReadingContent.Client();private readonly SummaryClient summaries=new();private readonly CancellationTokenSource stop=new();private readonly SemaphoreSlim sync=new(1),api=new(1);private readonly IdleGate idle=new();private readonly object gate=new();private CancellationTokenSource? worker;private bool workerImmediate;private string workerId="";private DateTimeOffset next=DateTimeOffset.MinValue;private readonly Task loop;private readonly Task monitor;private volatile bool mayWork;private volatile bool autoDue=true;private bool limitHit;private string autoDay="";
    internal ReadingSettings Settings {get;private set;}
    internal event Action? Updated;internal string Status {get;private set;}="阅读已启用";
    internal ReadingService(string directory,ReadingSettings settings){Settings=Clone(settings);store=new(directory);foreach(var s in ReadingCatalog.All())if(!store.Load<Source>("source").Any(x=>x.Id==s.Id))store.Put("source",s.Id,s);foreach(var j in store.Load<ReadJob>("job")){j.Status="等待闲置";j.Immediate=false;store.Put("job",j.Id,j);}store.Prune();monitor=Task.Run(Monitor);loop=Task.Run(Loop);}
    private static ReadingSettings Clone(ReadingSettings s)=>JsonSerializer.Deserialize<ReadingSettings>(JsonSerializer.Serialize(s))!;
    internal static ReadingSettings LoadSettings(string directory){try{return JsonSerializer.Deserialize<ReadingSettings>(File.ReadAllText(Path.Combine(directory,"reading-settings.json")))??new();}catch{return new();}}
    internal static void SaveSettings(string directory,ReadingSettings settings){Directory.CreateDirectory(directory);string path=Path.Combine(directory,"reading-settings.json");File.WriteAllText(path+".tmp",JsonSerializer.Serialize(settings));File.Move(path+".tmp",path,true);}
    internal void Configure(ReadingSettings settings){Settings=Clone(settings);autoDue=true;SaveSettings(Directory.GetParent(store.DirectoryPath)!.FullName,settings);Changed();}
    internal List<Source> Sources()=>store.Load<Source>("source");
    internal List<Article> Articles()=>store.Load<Article>("article");
    internal List<Article> Query(string day,string source,bool discovered,bool favorites,int offset)=>store.Query(day,source,discovered,favorites,offset);
    internal List<ReadJob> Jobs()=>store.Load<ReadJob>("job");
    internal void SaveSource(Source s){store.Put("source",s.Id,s);next=DateTimeOffset.MinValue;Changed();}
    internal void RemoveSource(Source s){s.Subscribed=false;SaveSource(s);if(s.Id.StartsWith("custom-"))store.Delete("source",s.Id);}
    internal void SaveArticle(Article a){store.Put("article",a.Id,a);Changed();}
    private void SaveContent(Article a){var latest=store.Find<Article>("article",a.Id);if(latest!=null){a.Read=latest.Read;a.Favorite=latest.Favorite;}SaveArticle(a);}
    private void Changed()=>Updated?.Invoke();
    internal void Queue(Article a,string file="",bool immediate=false){if(Jobs().Any(j=>j.ArticleId==a.Id))return;store.Put("job",a.Id,new ReadJob{Id=a.Id,ArticleId=a.Id,File=file,Immediate=immediate});a.Status=immediate?"准备精读":"等待闲置";SaveContent(a);}
    internal void RunNow(string id){var j=Jobs().FirstOrDefault(j=>j.Id==id);if(j!=null){j.Immediate=true;store.Put("job",id,j);lock(gate){if(workerId==id)workerImmediate=true;}Changed();}}
    internal void Cancel(string id){lock(gate){if(workerId==id)worker?.Cancel();}store.Delete("job",id);Changed();}
    internal Task Refresh()=>Task.Run(RefreshCore);
    private async Task RefreshCore(){if(!await sync.WaitAsync(0))return;try{if(!NetworkInterface.GetIsNetworkAvailable()){Status="网络不可用，保留已有文章。";return;}var sources=Sources().Where(s=>s.Subscribed&&(!s.NextAttempt.HasValue||s.NextAttempt<=DateTimeOffset.Now)).ToList();using var slots=new SemaphoreSlim(2);await Task.WhenAll(sources.Select(async s=>{await slots.WaitAsync(stop.Token);try{await Fetch(s);}finally{slots.Release();}}));Status="订阅检查完成；源失败与无新文章分别显示。";autoDue=true;next=DateTimeOffset.Now.AddHours(2);store.Prune();}catch(OperationCanceledException){}catch(Exception e){Status="阅读更新失败："+e.Message;}finally{sync.Release();Changed();}}
    private async Task Fetch(Source s){try{using var req=new HttpRequestMessage(HttpMethod.Get,s.Url);if(s.ETag.Length>0)req.Headers.TryAddWithoutValidation("If-None-Match",s.ETag);if(s.Modified.Length>0)req.Headers.TryAddWithoutValidation("If-Modified-Since",s.Modified);using var response=await http.SendAsync(req,HttpCompletionOption.ResponseHeadersRead,stop.Token);if(response.StatusCode==System.Net.HttpStatusCode.NotModified){s.Status="未更新（304）";}else{var bytes=await ReadingContent.Bounded(response,4_000_000,stop.Token);var parsed=ReadingContent.Parse(bytes,s);if(parsed.Count==0)throw new IOException("未解析到文章，请核对订阅源。" );foreach(var a in parsed){var old=store.Find<Article>("article",a.Id)??store.FindUrl(a.Url);if(old==null){if(s.LastSuccess==null&&a.PublishedDay!=null&&string.CompareOrdinal(a.PublishedDay,DateTime.Now.AddDays(-7).ToString("yyyy-MM-dd"))<0)continue;store.Put("article",a.Id,a);}else{bool changed=old.Abstract!=a.Abstract;old.Title=a.Title;old.Abstract=a.Abstract;if(a.PublishedDay!=null){old.PublishedDay=a.PublishedDay;old.DateEvidence=a.DateEvidence;}if(changed){old.SummaryKey="";old.Status="文章已更新，摘要待更新";}store.Put("article",old.Id,old);}}s.ETag=response.Headers.ETag?.ToString()??"";s.Modified=response.Content.Headers.LastModified?.ToString("R")??"";s.Status=$"更新成功 · {parsed.Count}条来源记录";}s.LastSuccess=DateTimeOffset.Now;s.NextAttempt=null;s.Failures=0;}catch(Exception e)when(e is not OperationCanceledException){s.Failures++;s.NextAttempt=DateTimeOffset.Now.AddMinutes(Math.Min(120,5*Math.Pow(2,Math.Min(s.Failures,5))));s.Status="更新失败："+(e is HttpRequestException h?$"HTTP {h.StatusCode}":e.Message);}finally{var latest=store.Find<Source>("source",s.Id);if(latest!=null){s.Subscribed=latest.Subscribed;store.Put("source",s.Id,s);}Changed();}}
    internal Task Summarize(Article a,bool automatic=false)=>Task.Run(()=>SummarizeCore(a,automatic));
    private async Task SummarizeCore(Article a,bool automatic){var config=Settings;if(!config.Ready||config.AbstractConsent!=config.Endpoint){Status="请在阅读设置中配置API并确认摘要发送范围。";Changed();return;}await api.WaitAsync(stop.Token);try{a=store.Find<Article>("article",a.Id)??a;if(a.Abstract.Length<100)await ArticleMetadata.Enrich(a,http,stop.Token);if(automatic&&a.PublishedDay!=DateTime.Now.ToString("yyyy-MM-dd")){SaveContent(a);return;}string key=ReadingCatalog.Hash(a.Abstract+config.Model+config.Endpoint+"short-v1");if(a.SummaryKey==key)return;if(a.Abstract.Length<100){a.Status="资料不足，打开原文查看";SaveContent(a);return;}if(automatic&&!store.Reserve(DateTime.Now.ToString("yyyy-MM-dd"),config.DailyLimit)){Status="今日自动摘要额度已用完";limitHit=true;return;}a.Status="正在总结";SaveContent(a);string result=await summaries.Ask(config,a.Title+"\n"+a.Abstract,false,stop.Token);a.ChineseTitle=result.Split('\n')[0].Trim('#',' ');a.Summary=result;a.SummaryKey=key;a.Status="基于摘要／导读";SaveContent(a);}catch(Exception e)when(e is not OperationCanceledException){a.Status=e.Message;SaveContent(a);}finally{api.Release();Changed();}}
    internal Task<string> Test()=>summaries.Ask(Settings,"这是一项连接测试。请回复：连接成功。",false,stop.Token);
    private async Task Monitor(){try{while(!stop.IsCancellationRequested){mayWork=idle.Allowed();lock(gate){if(!mayWork&&!workerImmediate)worker?.Cancel();}await Task.Delay(2000,stop.Token);}}catch(OperationCanceledException){}}
    private async Task Loop(){Task? heavy=null;try{while(!stop.IsCancellationRequested){bool allowed=mayWork;if(DateTimeOffset.Now>=next){await Refresh();next=DateTimeOffset.Now.AddMinutes(NetworkInterface.GetIsNetworkAvailable()?120:1);}if(heavy==null||heavy.IsCompleted){if(heavy!=null)await heavy;var job=Jobs().FirstOrDefault(j=>j.Immediate||allowed);if(job!=null){lock(gate){worker=CancellationTokenSource.CreateLinkedTokenSource(stop.Token);workerImmediate=job.Immediate;workerId=job.Id;}heavy=ProcessJob(job,worker.Token);}}
            if(autoDay!=DateTime.Now.ToString("yyyy-MM-dd")){autoDay=DateTime.Now.ToString("yyyy-MM-dd");autoDue=true;}
            if(autoDue&&NetworkInterface.GetIsNetworkAvailable()&&Settings.Automatic&&Settings.Ready&&Settings.AbstractConsent==Settings.Endpoint){autoDue=false;limitHit=false;var groups=store.Pending(DateTime.Now.ToString("yyyy-MM-dd"),Settings.DailyLimit).GroupBy(a=>a.SourceId).Select(g=>new Queue<Article>(g.OrderBy(a=>a.Discovered))).ToList();while(groups.Any(g=>g.Count>0)){foreach(var group in groups.Where(g=>g.Count>0)){await Summarize(group.Dequeue(),true);if(limitHit)break;}if(limitHit)break;}}
            await Task.Delay(2000,stop.Token);}}catch(OperationCanceledException){}finally{lock(gate){worker?.Cancel();}if(heavy!=null)try{await heavy;}catch{} }}
    private async Task ProcessJob(ReadJob job,CancellationToken ct){var config=Settings;try{if(store.Find<ReadJob>("job",job.Id)==null)return;ct.ThrowIfCancellationRequested();var a=store.Find<Article>("article",job.ArticleId);if(a==null){store.Delete("job",job.Id);return;}var s=Sources().FirstOrDefault(s=>s.Id==a.SourceId);job.Status="解析中";a.Status="正在提取全文";SaveContent(a);store.Put("job",job.Id,job);Changed();var result=await ReadingWorker.Launch(new WorkerRequest{Url=a.Url,File=job.File,Publisher=s?.Publisher??""},Path.Combine(store.DirectoryPath,"cache"),ct);if(result.Error.Length>0)throw new IOException(result.Error);string key=ReadingCatalog.Hash(result.Text+config.Model+config.Endpoint+"full-v1");if(a.FullKey!=key){if(config.FullConsent!=config.Endpoint)throw new IOException("请先确认全文发送到所选API服务。");await api.WaitAsync(ct);try{var chunks=Enumerable.Range(0,(result.Text.Length+11999)/12000).Select(i=>result.Text.Substring(i*12000,Math.Min(12000,result.Text.Length-i*12000))).ToList();var notes=new List<string>();foreach(var chunk in chunks)notes.Add(await summaries.Ask(config,a.Title+"\n资料范围："+result.Basis+"，以下可能为部分章节。\n"+chunk,true,ct));a.FullSummary=(chunks.Count==1?notes[0]:await summaries.Ask(config,"以下为各部分阅读笔记，请合成总结并保留页码/章节引用：\n"+string.Join("\n",notes),true,ct))+"\n\n依据："+result.Basis+(result.Complete?"；完整提取。":"；完整性未确认或部分提取。");a.FullKey=key;}finally{api.Release();}}a.Status="精读已完成";SaveContent(a);store.Delete("job",job.Id);}catch(OperationCanceledException){if(Jobs().Any(j=>j.Id==job.Id)){job.Status="等待闲置";job.Immediate=false;store.Put("job",job.Id,job);}}catch(Exception e){job.Status=e.Message;job.Immediate=false;store.Put("failed-job",job.Id,job);store.Delete("job",job.Id);var a=store.Find<Article>("article",job.ArticleId);if(a!=null){a.Status=e.Message;SaveContent(a);}}finally{lock(gate){worker?.Dispose();worker=null;workerId="";}store.Prune();Changed();}}
    public void Dispose(){stop.Cancel();lock(gate){worker?.Cancel();}_=loop.ContinueWith(_=>{http.Dispose();summaries.Dispose();stop.Dispose();});}
}
